### ISSUE TITLE
Implement get_key1 and get_key2

### ISSUE THREAD

**Issue by rizrmd** [thejpster/multi-map#14]
Thanks for great crate. After using this, I found myself needing to get the key instead of value, hence: 

- get_with_key1(key: K2) -> (K1, V)
- get_with_key2(key: K1) -> (K2, V)

is exactly what I need... thanks a bunch.

**Comment by hmuendel** [comment]
I think it is useful, otherwise it is cumbersome to keep track of the other key, while the map already has this relation stored.
I implemented a version with an interface, which appears more consistent, also the naming was normally. `get` and `get_alt`
```rust
get_with_key(&self, key: &K1) -> Option<(&K2, &V)>
get_mut_with_key(&mut self, key: &K1) -> Option<(&K2, &mut V)> 
get_alt_with_key(&self, key: &K2) -> Option<(&K1, &V)>
get_mut_alt_with_key(&mut self, key: &K2) -> Option<(&K1, &mut V)> 
```
hope this makes sense
https://github.com/rust-embedded-community/multi-map/pull/15

**Comment by rizrmd** [comment]
Fantastic! hope this get merged.
